#' The relevance adjusted goldfish v2
#' 
#' Calculates weights for which previous log scores to use based on the 
#' relevance adjusted caliper method. All observations within a certain
#' distance are given equal weight, all outside of that distance are given
#' zero weight.
#' 
#' @param t Positive integer greater than 2. This is the timepoint (relative to the notebook) for which we wish to make our prediction.
#' @param data Notebook containing all predictions, outcomes, covariates, and predictive distributions. Should be generated by notebook_bvar.
#' @param tol Determines how similar observations need to be to be included.

caliper_relevance <- function(t, data, tol) {
    
    weight_vec <- rep(0, nrow(data))

    if (t < 2) { stop("t needs to be 2 or greater") }
    index <- c()
    cov_vec <- data[t, 1:7]
    for (i in seq_len(t - 1)) {
        if (sum((cov_vec - data[i, 1:7])^2) < tol) {
            index <- c(index, i)
        }
    }
    
    weight_vec[index] <- 1 / length(index)
    return(weight_vec)
}