#' Mahalanobis relevance
#' 
#' Calculates weights for which previous log scores to use based on the
#' Mahalanobis distance. All observations are included, but the weights
#' decrease quickly as a funcion of the Mahalanobis distance. Note that
#' there is no Mahalanobisification done, so you have to use a rescaled
#' data set!
#' 
#' @param t Positive integer greater than 2. This is the timepoint (relative to the notebook) for which we wish to make our prediction.
#' @param data Notebook containing all predictions, outcomes, covariates, and predictive distributions. Should be generated by notebook_bvar.

mahalanobis_relevance <- function(t, data) {
    if (t < 2) { stop("t needs to be 2 or greater") }
    cov_vec <- data[t, 1:7]
    weight_vec <- rep(0, nrow(data))
    for (i in seq_len(t - 1)) {
        weight_vec[i] <- sum((cov_vec - data[i, 1:7])^2)
    }
    weight_vec <- weight_vec / sum(weight_vec)
    return(weight_vec)
}
