#' The relevance adjusted goldfish v2
#' 
#' Calculates weights for which previous log scores to use based on the 
#' relevance adjusted goldfish. The foldfish forgets everything that happened
#' more than ten minutes ago (in covariate space).
#' 
#' @param t Positive integer greater than 2. This is the timepoint (relative to the notebook) for which we wish to make our prediction.
#' @param data Notebook containing all predictions, outcomes, covariates, and predictive distributions. Should be generated by notebook_bvar.
#' @param tol Determines how similar observations need to be to be included.

relevance_goldfish_2 <- function(t, data, tol) {
    
    weight_vec <- rep(0, nrow(data))

    if (t < 2) { stop("t needs to be 2 or greater") }
    index <- c()
    cov_vec <- data[t, 1:7]
    for (i in seq_len(t - 1)) {
        if (sum((cov_vec - data[i, 1:7])^2) < tol) {
            index <- c(index, i)
        }
    }
    
    weight_vec[index] <- 1 / length(index)
    return(weight_vec)

}