#' The relevance adjusted goldfish
#' 
#' Calculates weights for which previous log scores to use based on the 
#' relevance adjusted goldfish.
#' 
#' @param t Positive integer greater than 2. This is the timepoint (relative to the notebook) for which we wish to make our prediction.
#' @param notebook Notebook containing all predictions, outcomes, covariates, and predictive distributions. Should be generated by notebook_bvar.
#' @param tol Determines how similar observations need to be to be included.

relevance_goldfish <- function(t, notebook, tol) {
    
    if (t < 2) { stop("t needs to be 2 or greater") }
    index <- c()
    cov_vec <- notebook[t, "cov"][[1]]
    for (i in seq_len(t-1)) {
        if (sum((cov_vec - notebook[i, "cov"][[1]])^2) < tol) {
            index <- c(index, i)
        }
    }
    return(index)
}